jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Set up variables for OS and Architecture
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            os="linux"
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            os="darwin"
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            os="windows"
          fi

          arch=$(uname -m)
          if [[ "$arch" == "x86_64" ]]; then
            arch="amd64"
          elif [[ "$arch" == "aarch64" ]]; then
            arch="arm64"
          fi

          echo "OS: $os"
          echo "Architecture: $arch"

          echo "os=$os" >> $GITHUB_ENV
          echo "arch=$arch" >> $GITHUB_ENV

      - name: Install terraform-docs
        run: |
          version=$(curl -s https://api.github.com/repos/terraform-docs/terraform-docs/releases/latest | jq -r .tag_name)
          curl -Lo /usr/local/bin/terraform-docs https://github.com/terraform-docs/terraform-docs/releases/download/${version}/terraform-docs-${version}-$os-$arch
          chmod +x /usr/local/bin/terraform-docs

      - name: Generate Terraform Docs
        run: terraform-docs markdown . > README.md

      - name: Commit Changes
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add README.md
          git commit -m "Update Terraform Docs"
          git push