##Here is the file for github actions
name: Generate Terraform Docs

on:
  # pull_request:
  #   types: [closed]
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  generate-docs:
    name: Generate Terraform Docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Download and Install terraform-docs
        run: |
          echo "Fetching the latest version of terraform-docs"

          # Fetch the latest version number dynamically
          version=$(curl -s https://api.github.com/repos/terraform-docs/terraform-docs/releases/latest | jq -r .tag_name)
          echo "Latest version of terraform-docs: $version"

          # Construct the download URL for terraform-docs tar.gz
          download_url="https://github.com/terraform-docs/terraform-docs/releases/download/${version}/terraform-docs-${version}-linux-amd64.tar.gz"
          echo "Download URL: $download_url"

          # Download the terraform-docs tar.gz file
          curl -Lo ./terraform-docs.tar.gz "$download_url"
          
          # Extract and install terraform-docs
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          sudo mv terraform-docs /usr/local/bin/terraform-docs

      - name: Verify terraform-docs installation
        run: |
          echo "Verifying the terraform-docs installation"
          ls -l /usr/local/bin/terraform-docs
          file /usr/local/bin/terraform-docs
          /usr/local/bin/terraform-docs --version  # Ensure it runs

      - name: Generate Terraform Docs
        run: |
          /usr/local/bin/terraform-docs markdown . > README.md

      - name: Commit Changes
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add README.md
          git commit -m "Update Terraform Docs"

      - name: Push changes to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin main