##Here is the file for github actions
name: Generate Terraform Docs

on:
  # pull_request:
  #   types: [closed]
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  generate-docs:
    name: Generate Terraform Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up OS and architecture
        run: |
          echo "Setting up OS and architecture"

          # Detect the OS from the GitHub runner environment
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            os="linux"
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            os="darwin"
          elif [[ "${{ runner.os }}" == "Windows" ]]; then
            os="windows"
          fi

          # Capture architecture using uname -m
          architecture=$(uname -m)

          # Normalize architecture names for terraform-docs
          if [[ "$architecture" == "x86_64" ]]; then
            architecture="amd64"
          elif [[ "$architecture" == "aarch64" ]]; then
            architecture="arm64"
          fi

          echo "OS: $os"
          echo "Architecture: $architecture"

          echo "os=$os" >> $GITHUB_ENV
          echo "architecture=$architecture" >> $GITHUB_ENV

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Download terraform-docs
        run: |
          version=$(curl -s https://api.github.com/repos/terraform-docs/terraform-docs/releases/latest | jq -r .tag_name)
          echo "Version of terraform-docs: $version"

          # Dynamically construct the download URL based on OS and architecture
          download_url="https://github.com/terraform-docs/terraform-docs/releases/download/${version}/terraform-docs-${version}-${os}-${architecture}"
          echo "Download URL: $download_url"

          # Download the appropriate terraform-docs binary
          curl -Lo /usr/local/bin/terraform-docs "$download_url"
          chmod +x /usr/local/bin/terraform-docs

      - name: Verify terraform-docs installation
        run: |
          echo "Verifying the terraform-docs installation"
          ls -l /usr/local/bin/terraform-docs
          file /usr/local/bin/terraform-docs
          /usr/local/bin/terraform-docs --version  # Ensure it runs

      - name: Generate Terraform Docs
        run: |
          /usr/local/bin/terraform-docs markdown . > README.md

      - name: Commit Changes
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add README.md
          git commit -m "Update Terraform Docs"
          git push